# Generated by Django 4.2.1 on 2023-06-11 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='topic',
            field=models.ForeignKey(db_column='', on_delete=django.db.models.deletion.CASCADE, related_name='topic_select', to='base.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
