# Generated by Django 4.2.1 on 2023-06-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_todo_topic_alter_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='topic',
        ),
        migrations.AddField(
            model_name='todo',
            name='topics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic'),
        ),
    ]
